name: 🐛 Bug melden
description: Etwas funktioniert nicht wie erwartet? Bitte gib uns möglichst viele Informationen.
title: "[Bug] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Danke, dass du einen Bug meldest! Bitte fülle die folgenden Felder so genau wie möglich aus.
  - type: input
    id: integration_version
    attributes:
      label: Version der Integration
      description: Welche Version deiner Custom Integration ist installiert?
      placeholder: z. B. v1.2.0 oder "aktueller main branch"
    validations:
      required: true
  - type: input
    id: ha_version
    attributes:
      label: Home Assistant Version
      description: Welche Home Assistant Version nutzt du?
      placeholder: z. B. 2024.5.2
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Was ist das Problem?
      description: Beschreibe den Fehler möglichst detailliert. Was hast du erwartet, was ist stattdessen passiert?
      placeholder: Fehlermeldung, unerwartetes Verhalten etc.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Schritte zur Reproduktion
      description: Wie kann man das Problem nachstellen?
      placeholder: |
        1. Konfiguration anpassen
        2. Home Assistant neu starten
        3. Fehler tritt auf
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logausgaben
      description: Füge relevante Logs aus dem Home Assistant Log hinzu, wenn vorhanden.
      render: shell
  - type: textarea
    id: config
    attributes:
      label: Relevanter Auszug aus der Konfiguration
      description: Falls zutreffend – teile den relevanten Teil deiner `configuration.yaml` oder UI-Einstellungen.
      render: yaml
  - type: dropdown
    id: wallbox_used
    attributes:
      label: Nutzt du das Wallbox Add-on?
      options:
        - Ja
        - Nein
      description: Falls ja, gib bitte sicher, dass das Add-on korrekt läuft und erreichbar ist.
